sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "node"
matrix:
  fast_finish: true
  allow_failures:
  - node_js: "4"
before_install:
  - npm i npm@^4 -g
install:
  - npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - npm run ci:travis
cache:
  directories:
    - node_modules
notifications:
  slack:
    secure: cd4+Br2krzmio2eFu6tekQ6/P2Az8/ShiGub7KXdjySaTR+dfIRs0Fvj15m+ccliERZt72rTOGwq+/m2lWWQyMIhwHISQQ+2+IUpRJeWWkmltq4F6VJCUqW+A8Tb/yHBHy3WDRZIG3eXy3s4xPfR1vjOjrflNzhHrm1awV68wUJnwGvGQ9y5kOiU3m2jvb3k7KiVU6p8Ki9dKjV33EitA23izW4vzBh67/5+VGwx8mwsQ8DtxAR+6HDV82vH0n5/MfNhLv73krKLo3XayV8mC9Co+PWFFXXEh0GEYWz9MxTHnv1G4RgjXzHec2truqpShQ37FQ0BWapvUZX98JEF7ocF6CBT6Em0yUytytefk8qWS+wxx0xOb2D0r0OEtF+DV2b4fOWDicWkwHPnU9tip2HFBfFiQLJlFJm3bQaLENqCIAfDJaRSPzkyx3ElY8UKj55TNlhxRzzMU7rve64LocP/nI1PsmXC2mux+gqwJD8FGuC/AYgeEos0/0W3Sdn4EPgTUZ8DyhShwLpNx7SDvVkoAPvTNZehvL5bIv6xT7lUt8JdxbBPqkY99G8AxUEkAp98qjPmUICND1jHBYE+GmbP0KSKp0AYNbY4SaN8cgu8E/u1TMefBp7NBenr4kMhWM7JD/mekkCe52klNtLZ/UOu+PN7i5QHs4887B1cUbw=
