sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "node"
matrix:
  fast_finish: true
  allow_failures:
  - node_js: "4"
before_install:
  - npm i npm@^4 -g
install:
  - npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - npm run ci:travis
cache:
  directories:
    - node_modules
notifications:
  slack:
    secure: Kg/BUigBw9WA7JDGsfFrC/yoS01FS8zQ2w4NHAcFFjb6wrcEF/jIWAr6xxevrRa1/M2fKmVM4z9fX+gqRLbW4y6MOoNDmekfllLXRRs3rcwFQ6B9Kxl9xgu1TKx3q0m9RwJSHnzZg6e6OzqaypX7gLpgJ9ml2DiVdVgpEHmtnoUm4E19z2lnGj6UuIAPOyWtUxxASiJsGGOkEJJGHx2h6UpLXEFVwSsi5l1wKVMHVMOw0Ye1fR4TOwFaN6YBTzEBDcZ3NgPs+JtNUF+oNu4kzaSV1DcI7+J45TUtDoJQRT3JcPPhfet6RWIxhGjwYn+rTSJZhirK5gdqyk6WOT8UJRjWTi0qs2R4UfM0SVbcNcxkmC0KeeXk5AYygOP0Cq+XnHn9w434bV+I94O9eXF5bNTVqQIVkpxnrUhUzZiKpWM4R5Es0QuTiOzMeCSI/wKQ2+fZLl+OT/0qRWTNIU9B5sAZ/7CVMLKAwcEFnBf1BscWE5moVb4TcNcoqyqMATEBknvUj7Cjhw+FN3xTBRL0XH9VMNAN1KcXM7G41/XbxV6OBHWHzwd5vzBdJ9+hXlKd4sImMRs+7xtDmbL5PR/p6nFnxPmVKPd1iEIQiRO79ZN8fSt1NBwBQMjS5jd1E+N8FtOPwVbFFDQXzqZgbS4w6+NBSk1EZ9uKt1pBGfIRJe0=
